title: 网络隐私工具 - 通过安全的加密抵抗全球大规模监控
description: 你正在被盯着！这里提供一些保护隐私和抵抗全球大规模监控的知识与工具。
url: "https://privacy-zh.yoitsu.moe"
sass:
  style: compressed
plugins:
  - jekyll-sitemap
sitemap:
file: "/sitemap.xml"
