title: PrivacyTools 网络隐私工具 - 通过安全的加密抵抗全球大规模监控
name: PrivacyTools
description: 老大哥在看着你！这里提供一些保护隐私和抵抗全球大规模监控的知识与工具。
url: "https://privacytools-zh-cn.yoitsu.moe"
production_url: "https://privacytools-zh-cn.yoitsu.moe"
sass:
  style: compressed
plugins:
  - jekyll-sitemap
sitemap:
file: "/sitemap.xml"
include: [".well-known"]
exclude: ["font", "vendor"]
destination: "./docs"